// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_xFZ-kz5OmDZ-ZPiq9Ovx68t6dgJtYTM',
    appId: '1:928088551795:web:68030e5111e3f06e765506',
    messagingSenderId: '928088551795',
    projectId: 'ecommerce-e1db4',
    authDomain: 'ecommerce-e1db4.firebaseapp.com',
    storageBucket: 'ecommerce-e1db4.appspot.com',
    measurementId: 'G-SFFWKL9E9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0HASYxjaznV2xgOsVjNs6lTQGEuq2iG0',
    appId: '1:928088551795:android:b5f1c1a31e81d01a765506',
    messagingSenderId: '928088551795',
    projectId: 'ecommerce-e1db4',
    storageBucket: 'ecommerce-e1db4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJAOyr1oN1i_TceG1Wfd_EpcK7UdAqTqw',
    appId: '1:928088551795:ios:08b3832815ebd8f2765506',
    messagingSenderId: '928088551795',
    projectId: 'ecommerce-e1db4',
    storageBucket: 'ecommerce-e1db4.appspot.com',
    iosClientId: '928088551795-jjtiupeev2lvkttckn7vi06mjeg6k5um.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJAOyr1oN1i_TceG1Wfd_EpcK7UdAqTqw',
    appId: '1:928088551795:ios:94361747c8bbc9a5765506',
    messagingSenderId: '928088551795',
    projectId: 'ecommerce-e1db4',
    storageBucket: 'ecommerce-e1db4.appspot.com',
    iosClientId: '928088551795-5iia62bhbce24tok1qgtpmvap11fqga8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
